version: '3.8'

services:
  viteapp:
    image: node:20-alpine3.16
    container_name: socialley-postgres-client
    ports:
      - "5225:8010"
    volumes:
      - "./:/app"
    working_dir: /app
    command: sh -c "npm install && npm run dev"